modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Team-Core/issues"
displayURL="https://u-team.info/mods/uteamcore"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"
    
[[mods]]
	modId="uteamtest_multiloader"
	version="${file.jarVersion}"
	displayName="U Team Test Multi Loader"
	description="This is just a test mod to test uteamcore"
	
	[[dependencies.uteamtest_multiloader]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"